language: python
branches:
  only:
  - master
install:
- pip install pelican Markdown ghp-import ipython beautifulsoup4 typogrify nbconvert
script:
- make publish
- make github 
env:
  global:
    secure: sX4DaplamtrfD1QjsKchS8/pmEPfzJH6lge/pxXJl4Gw0xrkKQkGXEbi881RwR1dpSVlF206NCxC4vg5rvzLKtFIZTBXlq4IHVU8GLGJdOCZtnuTafyK5/UWnWL8Ac+YBE4VrGLMW7i7vi7Zvv01DxACkXseNzl1qutVsjFFeVkeQt4z3XM8Dn2z1MYBFKkTbLX+ZXOsSNT6EhrA5qZCv/gEIYa7C9YmjjCp1kzyqjUAII/2bHIY5BcuAB31jYGrrVCX/3tKtzCVK14fkLaWl0ScnfG/k/gK85TT3F9XXAT05zhhN/tlgntk+xPHJJQPTCVEHlkvWLwZN+gZqJQ9/loSbWvwPRbINGkGpYlwxRUVkUilUhkIH4BAyLE32j3m0zbD5+aIB2EH7z9/QRHFcxv6jupN3U/cgfjlg9k3N4GClf4WKIF8BEWkoFc7+yl2jj0MBGOZYxu4h5oEzo4kV93lGw4WebKxMLrn/Cb+CCP4MCATNEndHPcP/yvj5NXL4E4UWJ9AkTi/pKkYW/NYcPjk0oB4W1JuFttdbbI2Ho6qjJA1hzxtoLx7qS2XpjQoINdHT9d4VuZt9N4wBiGQlHibzOeMMMhzCrm3RGdGuhLu6++GWv/o3iZWJPYcRCg83MFm6tY0JK9EIxhL6TRHDxUAiBU9n3WOVqDBJAB7tgE=
