version: '2'

services:
    python:
        build: 
            context: .
            dockerfile : Dockerfile
        image: blog:latest 
        ports:
            - "6969:6969"
        volumes:
            - ".:/site"
        tty: true
        working_dir: /site
        command: '/bin/bash'
        tty: true
        stdin_open: true

